server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /pet_imgs/ {
        alias /usr/share/nginx/html/pet_imgs/;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
